!!com.taobao.tae.config.domain.Config

#应用元信息
title: VGOGO开源的演示版本(DEMO)，不作为正式环境！
#网页标题的设置
description: VGOGO开源的演示版本(DEMO)，不作为正式环境！
language: php
author:  weron
thumbnail: /assets/images/logo.jpg

#type: 1 tae 模块 2 独立站点
type: 2

#全局css的配置
css: /assets/stylesheets/default.css

#首页 通过域名直接访问的页面如test.uz.taobao.com访问时的页面
index: /index.php


#http请求配置
urls:
#前端页面


#瀑布流的示例
#- {handler: /view/front/waterfall.php, url: /waterfall}

#filestore的demo，在应用中如何上传和下载文件
#- {handler: /tfs/tfs.php, url: /tfs}
#- {handler: /tfs/down.php, url: /down}
#- {handler: /tfs/upload.php, url: /upload}

#权限控制demo，只能站点所有者才能访问
#- {handler: /view/owner/owner.php, url: /owner}

#权限控制demo，只能登录用户才能访问
#- {handler: /view/custmor/custmor.php, url: /custmor}

#service demo ,演示如何实现mvc
#- {handler: /view/front/view.php, url: /view}
#- {handler: /view/front/report.php, url: /report}
##- {handler: /view/front/report_jsonp.php, url: /reportJsonp}
#- {handler: /view/front/vote_action.php, url: /voteAction}
#- {handler: /view/front/dnamicFunction.php, url: /dfi}


#安全和权限配置，默认是所有人都可以访问
#这个是前缀规则, url代表请求相对路径的前缀。
#role代表安全级别
#anonymous是任何用户都可以访问
#developer是站点所有者才能访问,
#shopcustomer 是表示登录用户可以访问

security:
#front下面页面都是所有人可以访问
#- {url: /view/front,role: anonymous }

#owner下面页面只有自己可以访问
- {url: /admin,role: developer }

#custmor下面页面只有登录可以访问
#- {url: /view/custmor,role: shopcustomer  }

